var rogue = new Listview({
  template: "spell",
  id: "spells",
  parent: "lv-generic",
  data: [
    {
      id: 1329,
      name: "@Mutilate",
      icon: "ability_rogue_shadowstrikes",
      level: 40,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [253],
      reagents: [],
      source: [9],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 13750,
      name: "@Adrenaline Rush",
      icon: "spell_shadow_shadowworddominate",
      level: 40,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [38],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 13877,
      name: "@Blade Flurry",
      icon: "ability_warrior_punishingblow",
      level: 30,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [38],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 14177,
      name: "@Cold Blood",
      icon: "spell_ice_lament",
      level: 30,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [253],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 14183,
      name: "@Premeditation",
      icon: "spell_shadow_possession",
      level: 20,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 14185,
      name: "@Preparation",
      icon: "spell_shadow_antishadow",
      level: 30,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 14251,
      name: "@Riposte",
      icon: "ability_warrior_challange",
      level: 20,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [38],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 14278,
      name: "@Ghostly Strike",
      icon: "spell_shadow_curse",
      level: 20,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 16511,
      name: "@Hemorrhage",
      icon: "spell_shadow_lifedrain",
      level: 30,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [9],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 32601,
      name: "@Surprise Attacks",
      icon: "ability_rogue_surpriseattack",
      level: 50,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [38],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 36554,
      name: "@Shadowstep",
      icon: "ability_rogue_shadowstep",
      level: 50,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 51662,
      name: "@Hunger For Blood",
      icon: "ability_rogue_hungerforblood",
      level: 60,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [253],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 51690,
      name: "@Killing Spree",
      icon: "ability_rogue_murderspree",
      level: 60,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [38],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 51713,
      name: "@Shadow Dance",
      icon: "ability_rogue_shadowdance",
      level: 60,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 58426,
      name: "@Overkill",
      icon: "ability_hunter_rapidkilling",
      level: 40,
      school: 1,
      cat: -2,
      trainingcost: 0,
      skill: [253],
      reagents: [],
      source: [9],
      reqclass: 8,
    },
    {
      id: 53,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 4,
      school: 1,
      cat: 7,
      trainingcost: 100,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 408,
      name: "@Kidney Shot",
      icon: "ability_rogue_kidneyshot",
      level: 30,
      school: 1,
      cat: 7,
      trainingcost: 10000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 703,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 14,
      school: 1,
      cat: 7,
      trainingcost: 1200,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 921,
      name: "@Pick Pocket",
      icon: "inv_misc_bag_11",
      level: 4,
      school: 1,
      cat: 7,
      trainingcost: 100,
      skill: [39],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 1725,
      name: "@Distract",
      icon: "ability_rogue_distract",
      level: 22,
      school: 1,
      cat: 7,
      trainingcost: 4000,
      skill: [39],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 1752,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 1,
      school: 1,
      cat: 7,
      trainingcost: 0,
      skill: [38],
      reagents: [],
      source: [10],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 1757,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 6,
      school: 1,
      cat: 7,
      trainingcost: 100,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 1758,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 14,
      school: 1,
      cat: 7,
      trainingcost: 1200,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 1759,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 22,
      school: 1,
      cat: 7,
      trainingcost: 4000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 1760,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 30,
      school: 1,
      cat: 7,
      trainingcost: 10000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 1766,
      name: "@Kick",
      icon: "ability_kick",
      level: 12,
      school: 1,
      cat: 7,
      trainingcost: 800,
      skill: [38],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 1776,
      name: "@Gouge",
      icon: "ability_gouge",
      level: 6,
      school: 1,
      cat: 7,
      trainingcost: 100,
      skill: [38],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 1784,
      name: "@Stealth",
      icon: "ability_stealth",
      level: 1,
      school: 1,
      cat: 7,
      trainingcost: 10,
      skill: [39],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 1833,
      name: "@Cheap Shot",
      icon: "ability_cheapshot",
      level: 26,
      school: 1,
      cat: 7,
      trainingcost: 6000,
      skill: [253],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 1842,
      name: "@Disarm Trap",
      icon: "spell_shadow_grimward",
      level: 30,
      school: 1,
      cat: 7,
      trainingcost: 10000,
      skill: [39],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 1856,
      name: "@Vanish",
      icon: "ability_vanish",
      level: 22,
      school: 1,
      cat: 7,
      trainingcost: 4000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 1857,
      name: "@Vanish",
      icon: "ability_vanish",
      level: 42,
      school: 1,
      cat: 7,
      trainingcost: 27000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 1860,
      name: "@Safe Fall",
      icon: "inv_feather_01",
      level: 40,
      school: 1,
      cat: 7,
      trainingcost: 20000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Passive",
      reqclass: 8,
    },
    {
      id: 1943,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 20,
      school: 1,
      cat: 7,
      trainingcost: 3000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 1966,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 16,
      school: 1,
      cat: 7,
      trainingcost: 1800,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 2070,
      name: "@Sap",
      icon: "ability_sap",
      level: 28,
      school: 1,
      cat: 7,
      trainingcost: 8000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 2094,
      name: "@Blind",
      icon: "spell_shadow_mindsteal",
      level: 34,
      school: 1,
      cat: 7,
      trainingcost: 14000,
      skill: [39],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 2098,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 1,
      school: 1,
      cat: 7,
      trainingcost: 0,
      skill: [253],
      reagents: [],
      source: [10],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 2589,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 12,
      school: 1,
      cat: 7,
      trainingcost: 800,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 2590,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 20,
      school: 1,
      cat: 7,
      trainingcost: 3000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 2591,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 28,
      school: 1,
      cat: 7,
      trainingcost: 8000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 2836,
      name: "@Detect Traps",
      icon: "ability_spy",
      level: 24,
      school: 1,
      cat: 7,
      trainingcost: 5000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Passive",
      reqclass: 8,
    },
    {
      id: 2983,
      name: "@Sprint",
      icon: "ability_rogue_sprint",
      level: 10,
      school: 1,
      cat: 7,
      trainingcost: 300,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 5171,
      name: "@Slice and Dice",
      icon: "ability_rogue_slicedice",
      level: 10,
      school: 1,
      cat: 7,
      trainingcost: 300,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 5277,
      name: "@Evasion",
      icon: "spell_shadow_shadowward",
      level: 8,
      school: 1,
      cat: 7,
      trainingcost: 200,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 5938,
      name: "@Shiv",
      icon: "inv_throwingknife_04",
      level: 70,
      school: 1,
      cat: 7,
      trainingcost: 100000,
      skill: [38],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 6760,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 8,
      school: 1,
      cat: 7,
      trainingcost: 200,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 6761,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 16,
      school: 1,
      cat: 7,
      trainingcost: 1800,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 6762,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 24,
      school: 1,
      cat: 7,
      trainingcost: 5000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 6768,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 28,
      school: 1,
      cat: 7,
      trainingcost: 8000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 6770,
      name: "@Sap",
      icon: "ability_sap",
      level: 10,
      school: 1,
      cat: 7,
      trainingcost: 300,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 6774,
      name: "@Slice and Dice",
      icon: "ability_rogue_slicedice",
      level: 42,
      school: 1,
      cat: 7,
      trainingcost: 27000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 8621,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 38,
      school: 1,
      cat: 7,
      trainingcost: 18000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 8623,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 32,
      school: 1,
      cat: 7,
      trainingcost: 12000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 8624,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 40,
      school: 1,
      cat: 7,
      trainingcost: 20000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 8631,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 22,
      school: 1,
      cat: 7,
      trainingcost: 4000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 8632,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 30,
      school: 1,
      cat: 7,
      trainingcost: 10000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 8633,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 38,
      school: 1,
      cat: 7,
      trainingcost: 18000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 8637,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 40,
      school: 1,
      cat: 7,
      trainingcost: 20000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 8639,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 28,
      school: 1,
      cat: 7,
      trainingcost: 8000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 8640,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 36,
      school: 1,
      cat: 7,
      trainingcost: 16000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 8643,
      name: "@Kidney Shot",
      icon: "ability_rogue_kidneyshot",
      level: 50,
      school: 1,
      cat: 7,
      trainingcost: 35000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 8647,
      name: "@Expose Armor",
      icon: "ability_warrior_riposte",
      level: 14,
      school: 1,
      cat: 7,
      trainingcost: 1200,
      skill: [253],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 8676,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 18,
      school: 1,
      cat: 7,
      trainingcost: 2900,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 8696,
      name: "@Sprint",
      icon: "ability_rogue_sprint",
      level: 34,
      school: 1,
      cat: 7,
      trainingcost: 14000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 8721,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 36,
      school: 1,
      cat: 7,
      trainingcost: 16000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 8724,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 26,
      school: 1,
      cat: 7,
      trainingcost: 6000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 8725,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 34,
      school: 1,
      cat: 7,
      trainingcost: 14000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 11267,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 42,
      school: 1,
      cat: 7,
      trainingcost: 27000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 11268,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 50,
      school: 1,
      cat: 7,
      trainingcost: 35000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 11269,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 58,
      school: 1,
      cat: 7,
      trainingcost: 52000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 11273,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 44,
      school: 1,
      cat: 7,
      trainingcost: 29000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 11274,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 52,
      school: 1,
      cat: 7,
      trainingcost: 46000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 11275,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 60,
      school: 1,
      cat: 7,
      trainingcost: 54000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 11279,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 44,
      school: 1,
      cat: 7,
      trainingcost: 29000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 11280,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 52,
      school: 1,
      cat: 7,
      trainingcost: 46000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 7",
      reqclass: 8,
    },
    {
      id: 11281,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 60,
      school: 1,
      cat: 7,
      trainingcost: 54000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 8",
      reqclass: 8,
    },
    {
      id: 11289,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 46,
      school: 1,
      cat: 7,
      trainingcost: 31000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 11290,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 54,
      school: 1,
      cat: 7,
      trainingcost: 48000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 11293,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 46,
      school: 1,
      cat: 7,
      trainingcost: 31000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 7",
      reqclass: 8,
    },
    {
      id: 11294,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 54,
      school: 1,
      cat: 7,
      trainingcost: 48000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 8",
      reqclass: 8,
    },
    {
      id: 11297,
      name: "@Sap",
      icon: "ability_sap",
      level: 48,
      school: 1,
      cat: 7,
      trainingcost: 33000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 11299,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 48,
      school: 1,
      cat: 7,
      trainingcost: 33000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 7",
      reqclass: 8,
    },
    {
      id: 11300,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 56,
      school: 1,
      cat: 7,
      trainingcost: 50000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 8",
      reqclass: 8,
    },
    {
      id: 11303,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 52,
      school: 1,
      cat: 7,
      trainingcost: 46000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 11305,
      name: "@Sprint",
      icon: "ability_rogue_sprint",
      level: 58,
      school: 1,
      cat: 7,
      trainingcost: 52000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 17347,
      name: "@Hemorrhage",
      icon: "spell_shadow_lifedrain",
      level: 46,
      school: 1,
      cat: 7,
      trainingcost: 384,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 17348,
      name: "@Hemorrhage",
      icon: "spell_shadow_lifedrain",
      level: 58,
      school: 1,
      cat: 7,
      trainingcost: 650,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 25300,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 60,
      school: 1,
      cat: 7,
      trainingcost: 72000,
      skill: [38],
      reagents: [],
      source: [2, 6],
      rank: "Rank 9",
      reqclass: 8,
    },
    {
      id: 25302,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 60,
      school: 1,
      cat: 7,
      trainingcost: 50000,
      skill: [38],
      reagents: [],
      source: [2, 6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 26669,
      name: "@Evasion",
      icon: "spell_shadow_shadowward",
      level: 50,
      school: 1,
      cat: 7,
      trainingcost: 35000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 26679,
      name: "@Deadly Throw",
      icon: "inv_throwingknife_06",
      level: 64,
      school: 1,
      cat: 7,
      trainingcost: 72000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 26839,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 61,
      school: 1,
      cat: 7,
      trainingcost: 50000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 7",
      reqclass: 8,
    },
    {
      id: 26861,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 62,
      school: 1,
      cat: 7,
      trainingcost: 50000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 9",
      reqclass: 8,
    },
    {
      id: 26862,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 70,
      school: 1,
      cat: 7,
      trainingcost: 100000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 10",
      reqclass: 8,
    },
    {
      id: 26863,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 68,
      school: 1,
      cat: 7,
      trainingcost: 110000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 10",
      reqclass: 8,
    },
    {
      id: 26864,
      name: "@Hemorrhage",
      icon: "spell_shadow_lifedrain",
      level: 70,
      school: 1,
      cat: 7,
      trainingcost: 2700,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 26865,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 64,
      school: 1,
      cat: 7,
      trainingcost: 140000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 10",
      reqclass: 8,
    },
    {
      id: 26867,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 68,
      school: 1,
      cat: 7,
      trainingcost: 120000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 7",
      reqclass: 8,
    },
    {
      id: 26884,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 70,
      school: 1,
      cat: 7,
      trainingcost: 100000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 8",
      reqclass: 8,
    },
    {
      id: 26889,
      name: "@Vanish",
      icon: "ability_vanish",
      level: 62,
      school: 1,
      cat: 7,
      trainingcost: 59000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 27441,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 66,
      school: 1,
      cat: 7,
      trainingcost: 80000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 7",
      reqclass: 8,
    },
    {
      id: 27448,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 64,
      school: 1,
      cat: 7,
      trainingcost: 72000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 31016,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 60,
      school: 1,
      cat: 7,
      trainingcost: 65000,
      skill: [253],
      reagents: [],
      source: [2, 6],
      rank: "Rank 9",
      reqclass: 8,
    },
    {
      id: 31224,
      name: "@Cloak of Shadows",
      icon: "spell_shadow_nethercloak",
      level: 66,
      school: 1,
      cat: 7,
      trainingcost: 89000,
      skill: [39],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 32645,
      name: "@Envenom",
      icon: "ability_rogue_disembowel",
      level: 62,
      school: 8,
      cat: 7,
      trainingcost: 59000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 1",
      reqclass: 8,
    },
    {
      id: 32684,
      name: "@Envenom",
      icon: "ability_rogue_disembowel",
      level: 69,
      school: 8,
      cat: 7,
      trainingcost: 100000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 34411,
      name: "@Mutilate",
      icon: "ability_rogue_shadowstrikes",
      level: 50,
      school: 1,
      cat: 7,
      trainingcost: 5500,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 34412,
      name: "@Mutilate",
      icon: "ability_rogue_shadowstrikes",
      level: 60,
      school: 1,
      cat: 7,
      trainingcost: 6500,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 34413,
      name: "@Mutilate",
      icon: "ability_rogue_shadowstrikes",
      level: 70,
      school: 1,
      cat: 7,
      trainingcost: 7500,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 48637,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 76,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 11",
      reqclass: 8,
    },
    {
      id: 48638,
      name: "@Sinister Strike",
      icon: "spell_shadow_ritualofsacrifice",
      level: 80,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 12",
      reqclass: 8,
    },
    {
      id: 48656,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 74,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 11",
      reqclass: 8,
    },
    {
      id: 48657,
      name: "@Backstab",
      icon: "ability_backstab",
      level: 80,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 12",
      reqclass: 8,
    },
    {
      id: 48658,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 72,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 7",
      reqclass: 8,
    },
    {
      id: 48659,
      name: "@Feint",
      icon: "ability_rogue_feint",
      level: 78,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [38],
      reagents: [],
      source: [6],
      rank: "Rank 8",
      reqclass: 8,
    },
    {
      id: 48660,
      name: "@Hemorrhage",
      icon: "spell_shadow_lifedrain",
      level: 80,
      school: 1,
      cat: 7,
      trainingcost: 15000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 48663,
      name: "@Mutilate",
      icon: "ability_rogue_shadowstrikes",
      level: 75,
      school: 1,
      cat: 7,
      trainingcost: 15000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 5",
      reqclass: 8,
    },
    {
      id: 48666,
      name: "@Mutilate",
      icon: "ability_rogue_shadowstrikes",
      level: 80,
      school: 1,
      cat: 7,
      trainingcost: 15000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 6",
      reqclass: 8,
    },
    {
      id: 48667,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 73,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 11",
      reqclass: 8,
    },
    {
      id: 48668,
      name: "@Eviscerate",
      icon: "ability_rogue_eviscerate",
      level: 79,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 12",
      reqclass: 8,
    },
    {
      id: 48671,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 74,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 8",
      reqclass: 8,
    },
    {
      id: 48672,
      name: "@Rupture",
      icon: "ability_rogue_rupture",
      level: 79,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 9",
      reqclass: 8,
    },
    {
      id: 48673,
      name: "@Deadly Throw",
      icon: "inv_throwingknife_06",
      level: 70,
      school: 1,
      cat: 7,
      trainingcost: 100000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 2",
      reqclass: 8,
    },
    {
      id: 48674,
      name: "@Deadly Throw",
      icon: "inv_throwingknife_06",
      level: 76,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 48675,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 75,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 9",
      reqclass: 8,
    },
    {
      id: 48676,
      name: "@Garrote",
      icon: "ability_rogue_garrote",
      level: 80,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 10",
      reqclass: 8,
    },
    {
      id: 48689,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 70,
      school: 1,
      cat: 7,
      trainingcost: 140000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 8",
      reqclass: 8,
    },
    {
      id: 48690,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 75,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 9",
      reqclass: 8,
    },
    {
      id: 48691,
      name: "@Ambush",
      icon: "ability_rogue_ambush",
      level: 80,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 10",
      reqclass: 8,
    },
    {
      id: 51699,
      name: "@Honor Among Thieves",
      icon: "ability_rogue_honoramongstthieves",
      level: 0,
      school: 1,
      cat: 7,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [],
      reqclass: 8,
    },
    {
      id: 51722,
      name: "@Dismantle",
      icon: "ability_rogue_dismantle",
      level: 20,
      school: 1,
      cat: 7,
      trainingcost: 3000,
      skill: [253],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 51723,
      name: "@Fan of Knives",
      icon: "ability_rogue_fanofknives",
      level: 80,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [38],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 51724,
      name: "@Sap",
      icon: "ability_sap",
      level: 71,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [39],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 57933,
      name: "@Tricks of the Trade",
      icon: "ability_rogue_tricksofthetrade",
      level: 75,
      school: 1,
      cat: 7,
      trainingcost: 0,
      skill: [39],
      reagents: [],
      source: [],
      reqclass: 8,
    },
    {
      id: 57934,
      name: "@Tricks of the Trade",
      icon: "ability_rogue_tricksofthetrade",
      level: 75,
      school: 1,
      cat: 7,
      trainingcost: 300000,
      skill: [39],
      reagents: [],
      source: [6],
      reqclass: 8,
    },
    {
      id: 57992,
      name: "@Envenom",
      icon: "ability_rogue_disembowel",
      level: 74,
      school: 8,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 3",
      reqclass: 8,
    },
    {
      id: 57993,
      name: "@Envenom",
      icon: "ability_rogue_disembowel",
      level: 80,
      school: 8,
      cat: 7,
      trainingcost: 300000,
      skill: [253],
      reagents: [],
      source: [6],
      rank: "Rank 4",
      reqclass: 8,
    },
    {
      id: 58428,
      name: "@Serverside - Overkill - aura remove spell",
      icon: "inv_misc_questionmark",
      level: 0,
      school: 1,
      cat: 7,
      trainingcost: 0,
      skill: [253],
      reagents: [],
      source: [],
      reqclass: 8,
    },
  ],
  name: LANG.tab_spells,
  visibleCols: ["level", "singleclass", "schools", "trainingcost"],
});
